[platformio]
src_dir = examples/basic_shell
test_dir = test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    knolleary/PubSubClient @ ^2.8
lib_extra_dirs =
    .

[env:test]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    knolleary/PubSubClient @ ^2.8
lib_extra_dirs =
    .
lib_ldf_mode = deep
test_build_src = no
test_framework = unity
